### ISSUE TITLE
Add Stronghold sheets

### ISSUE THREAD

**Issue by orffen** [orffen/basicfantasyrpg#49]
# Strongholds
The sheet will be for calculating building costs and for combat use; maps and other details should be tracked in Description, or Journal entries, Scenes etc.

## Followers
- add a field to track how many are at the stronghold

## Floors
- floors should be a section on the sheet
- a container to hold walls; similar to spell slots, but there will be a dynamic number of floors (can be added/removed as needed)
- track square feet per floor (used in cost calculation) - calculated at 1' thick wood walls
- track total cost per floor
- floors are 10' high

## Walls
- HP/gp is the same value so only need one field
- hardness (autocalc based on material)
- thickness
- material (wood, brick, soft stone, hard stone) - selectable
- breaches will need to be manually tracked and calculated by players
- interior vs. exterior walls ~(no difference really) - don't need to track separately~ - exterior could be used in calculating floor area, but for non-rectangular floors it becomes complicated since the sheet won't track shapes

## Roofs
- effectively 1' thick wood walls

## Costs/Time
- engineering costs and time are + 0.1 * floors
- a multiplier is possible at GM discretion - this can be handled manually by the GM or noted in description
- guildhouses and towers "usually" have higher costs; but this can be manually applied by the GM; maybe a multiplier field is a good idea so cost can be automatically calculated

**Comment by miqued** [comment]
This looks great. I'd have to see what you mean about tracking walls like spell slots, I can't imagine that thought, it's just not clicking for me.

I'm trying to think of a way to make tracking breaches easy. It'd be neat to be able to drag a wall from the sheet onto the grid and be able to track HP only for sections of wall that have been hit; whether it reports back to the sheet doesn't seem important to me. I also don't think it's necessary to have the walls be proper actors, since the Target AC is tracked with the siege engines. Being able to look at the map of a stronghold and see at a glance where it's been hit and breached has a lot of value if it can be pulled off. I'll try and sketch out what I'm thinking, and maybe that'll help determine how it might be done.

This sheet will definitely take a lot of mathematical burden off by letting the user see the results as they tinker with their stronghold plans.

**Comment by orffen** [comment]
I have a sheet started; just adding some notes for when I continue working on it:

- `actor-sheet.mjs` will need updating for `floor` and `wall` types in `_prepareItems(context)`
- `wall` types need to add something like the `prepared` value in spells, including updates in above file for handling increment/decrement
- `actor-floors.html` will need to loop through floors and walls; floors are a 'heading' but need a way to edit them as well (add edit button)

**Comment by orffen** [comment]
It's taken a while, but we're ready for release!

![image](https://github.com/orffen/basicfantasyrpg/assets/2225985/d254fada-d94f-4d2e-8673-3d8713bf4a91)
