### ISSUE TITLE
Add Vehicle sheets

### ISSUE THREAD

**Issue by orffen** [orffen/basicfantasyrpg#50]
See #39

# Vehicles
- Vehicle facing exists by default (tokens can be rotated on the map)

## Length & Width/Weight
- Could be noted in description
- Alternatively, can a token be automatically scaled based on these values? How does that work in Foundry?
- Weight not needed, can just be noted in description

## AC
- Always AC 11, but this should be an editable field for exotic vehicles (e.g. a GM may want a heavily armoured tank in their game)

## Movement & Miles/Day
- Speed in both yards and miles per day
- halved if one "side" of HP is gone (can automate)
- track as "base movement", and "effective movement" (in case it is modified by damage)

## Hardness
- Hardness reduces damage (never changes)
- will be useful if additional automation is added in the future; for now just a stored value

## HP
- appears to be per side? rules unclear, but looks like we will need to track 4 values of HP, one for each side
    - 4 separate resource tracks; can they show on the token and be placed on the correct side?
    - port/starboard for sides
    - fore/aft or front/rear?
- if one entire side is gone, speed is halved (wheel damage or hull breach); can be automated
- if 2 sides take this much, immobilized - or sunk if a ship; can be automated
- might need to handle hull breach/sunk separately, but this can also just be a message on the sheet (players will know what's going on)

## Maneuverability
- Useful if this *optional* rule is being used, could be a field or just noted in description
- Has to be manually applied by players/GMs; nothing in Foundry can utilise it as far as I'm aware

## Cargo
~- Cargo can be tracked, but no mechanics listed; could be noted in description instead~
- We can have a cargo list ~(but that requires a 'cargo' type item)~; use the generic item, and track encumbrance as normal

## Crew
- Crew can be put into description; not really important enough to track on the sheet specifically

**Comment by miqued** [comment]
I like this.

Length/Width: I would put it in the description but also represented in the token. I don't know whether Foundry can auto-scale tokens, but I don't think the System will have to account for this either. Rather, the modules with vehicles should have the token scaled appropriately, and custom vehicles would need to be scaled anyway. I'll have to test this. There should be some consensus for the exact scale, however. The scale for outdoor and waterborne travel is given as yards in the rulebook, so that implies a 1 grid unit equals 1 yard. However, all movement, including characters in foot, occurs in multiples of 10 yards outdoors, so there's reason to use a 10 yard scale for simplicity as well.

HP: yes, it is per side. i.e. the Caravel has 75HP on the port side and 75 on starboard. The way I read the rules on immobilizing/sinking a vehicle, I am interpreting it to mean a vehicle only has two "sides" regardless of the actual shape of it, but if I'm wrong then I'm wrong. I don't know whether the resource bars can be arranged around tokens, but if not, maybe they can be labeled. Port/Star[board], P/S, Left/Right, L/R, or anything like that, though I'd lean to more universal Left/Right (and Front/Rear if used) labels, because carts don't pull into port. 😆

Cargo: I envisioned just an inventory list with the title "Cargo" rather than "Inventory". The core rulebook doesn't have trade goods, but the Equipment Emporium is full of stuff like that. Even if that particular supplement isn't being used, the cargo area of a vehicle sheet can be used by the GM for e.g. ships the party boards and loots, abandoned carts they come across, things like that. Players could also use it to track stored gear; my players throw lots of things "on the cart".

Everything I didn't mention seems good to me, and I agree with the approach for those things.

**Comment by orffen** [comment]
For HP, I'm canvassing some opinions from the community however it's occurred to me that I may as well add 4 sides for tracking HP - GMs who only want to use 2 can still do that, since the rules don't fundamentally change how vehicle speed/mobility/sinking is affected if there are more than 2 sides.

Vehicle weight does not appear to be used at all in the rules, so this will just be left out of the sheet - can be added to the description if a GM wants to track it for some reason.

**Comment by orffen** [comment]
Completed under commit 5e64fa4c7447e1cb1353d47e3f4f13394b2c5658
