### ISSUE TITLE
get a translation

### ISSUE THREAD

**Issue by Abeille128** [orffen/basicfantasyrpg#66]
I see you think about translate your system, and it interest me a lot to, so if you can add it to https://weblate.foundryvtt-hub.com to be translated, I can made it for you in French. thx for all your work.

**Comment by orffen** [comment]
That would be great! I’m currently travelling but will find some time to get this setup.


On 19 May 2024, at 06:00, Abeille128 ***@***.***> wrote:

﻿

I see you think about translate your system, and it interest me a lot to, so if you can add it to https://weblate.foundryvtt-hub.com<https://weblate.foundryvtt-hub.com/> to be translated, I can made it for you in French. thx for all your work.

**Comment by orffen** [comment]
I've submitted the project but have not heard back for over a week, am following up on the Foundry Hub Discord. May need an alternative solution.

Otherwise, `en.json` can be copied to `fr.json` and manually edited. @Abeille128 if you're comfortable working that way and with Git, you can create a fork and a branch for the translation and submit a pull request when ready.

**Comment by Abeille128** [comment]
ok thx i will look at it. I'm not sure to now how this work but il will try.

**Comment by orffen** [comment]
Thank you for this! Merged #70
