### ISSUE TITLE
FoundryVTT 12 compatibility

### ISSUE THREAD

**Issue by orffen** [orffen/basicfantasyrpg#67]
Validate compatibility with v12 and resolve warnings/errors

**Comment by DC23** [comment]
I'm working on this and should have a PR within a day or so. It will have the fix for #71 mixed in. I haven't looked at anything else you might have originally planned for the r14 milestone. I could do that at some point, but we'd probably need to have a chat about me coming on as a co-maintainer or developer on the project, which I'm happy to do but that's a conversation we'd need to have since it's your project. I'm also happy to keep working via PRs and leave the planning to you :)
